### ISSUE TITLE
Auth / Python Error when running script

### ISSUE THREAD

**Issue by mmaechtel** [htwg-syslab/syslab-reviewer#6]
```
AuthenticatedUser(login=None)
Traceback (most recent call last):
  File "htwg/syslab/reviewer/main.py", line 136, in <module>
    main()
  File "htwg/syslab/reviewer/main.py", line 129, in main
    github(term)
  File "htwg/syslab/reviewer/main.py", line 51, in github
    print('You are logged in as: {} ({})'.format(user.name, t.bold(user.login)))
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/AuthenticatedUser.py", line 221, in name
    self._completeIfNotSet(self._name)
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/GithubObject.py", line 251, in _completeIfNotSet
    self._completeIfNeeded()
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/GithubObject.py", line 255, in _completeIfNeeded
    self.__complete()
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/GithubObject.py", line 260, in __complete
    self._url.value
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 172, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, cnx))
  File "/Users/maechtel/.pyenv/versions/3.6.1/lib/python3.6/site-packages/github/Requester.py", line 180, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {'message': 'Bad credentials', 'documentation_url': 'https://developer.github.com/v3'}
```

Whats going wrong? I've set the token in `.syslab-reviewer.yml`

**Comment by SWW13** [comment]
Still works for me, even with upgraded dependencies.

Is the `.syslab-reviewer.yml` in `$HOME` and correct formated (https://raw.githubusercontent.com/htwg-syslab/syslab-reviewer/master/config/syslab-reviewer.sample.yml)?

Does the token have `repo` access?
![image](https://user-images.githubusercontent.com/1280142/32225557-def68882-be45-11e7-8825-e81c681d04ad.png)

You could also try to recreate the login token.

**Comment by mmaechtel** [comment]
Arghhh! 🤕  I had `.syslab-reviewer.yml` in the syslabXX dir not in my $HOME !

Many thanks !!
